config/routes.rb
Wedding::Application.routes.draw do
  mount API => '/'
  get 'sessions/new'

  get 'users/new'

  post 'index_datatable'=> 'invitees#index_datatable'
  post 'destroy_by_index'=> 'invitees#destroy_by_index'
  resources :invitees do
    member do
      get 'rsvp_main'
      get 'rsvp_result'
    end
    collection { post :import }
  end
  
  resource :invitees, only: :index do
    post 'mass_email', action: :mass_email
  end

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

end

app/models/invitee.rb
require 'csv'

class Invitee < ActiveRecord::Base
  attr_accessor :is_attending_patch

  before_save :set_uuid

  def self.import(file)
    allowed_attributes = ["name", "addressee", "max_guests", "email"]
    CSV.foreach(file.path, headers: true, :col_sep => ";") do |row|
      invitee = find_by_uuid(row["id"]) || new
      invitee.attributes = row.to_hash.select { |k,v| allowed_attributes.include? k }
      invitee.save!
    end
  end

  def to_param
    uuid
  end

  private
    
    def set_uuid
      self.uuid = SecureRandom.uuid if !self.uuid
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 } 

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/invitees_controller.rb
class InviteesController < ApplicationController
  before_action :set_invitee, only: [:show, :edit, :update, :destroy]

  # GET /invitees
  # GET /invitees.json
  def index
    @invitees = Invitee.all
  end

  def index_datatable
    @invitees = nil #Invitee.all
    respond_to do |format|
      format.html
      format.json {
        render json: InviteesDatatable.new(view_context)
      }
    end
  end

  # GET /invitees/1
  # GET /invitees/1.json
  def show
    @invitee = Invitee.find_by_uuid(params[:id])
  end

  # GET /invitees/new
  def new
    @invitee = Invitee.new
  end

  # GET /invitees/1/edit
  def edit
  end

  # POST /invitees
  # POST /invitees.json
  def create
    @invitee = Invitee.new(invitee_params)

    respond_to do |format|
      if @invitee.save
        format.html { redirect_to @invitee, notice: 'Invitee was successfully created.' }
        format.json { render action: 'show', status: :created, location: @invitee }
      else
        format.html { render action: 'new' }
        format.json { render json: @invitee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invitees/1
  # PATCH/PUT /invitees/1.json
  def update
    respond_to do |format|
      is_attending_patch = params[:invitee][:is_attending_patch]
      if params[:invitee][:number].to_i > 0
        params[:invitee][:attending] = true
      else
        params[:invitee][:attending] = false
      end
      if !params[:invitee][:attending]
        params[:invitee][:number] = 0
      end
      if @invitee.update(invitee_params)
        if is_attending_patch
          WeddingMailer.rsvp_email(@invitee).deliver
          format.html { redirect_to rsvp_result_invitee_path(@invitee) }
        else
          format.html { redirect_to @invitee, notice: 'Invitee was successfully updated.' }
        end

        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @invitee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invitees/1
  # DELETE /invitees/1.json
  def destroy
    @invitee.destroy
    respond_to do |format|
      format.html { redirect_to invitees_url }
      format.json { head :no_content }
    end
  end

  def destroy_by_index
    if params[:index] == 'all'
      Invitee.destroy_all
    else
      Invitee.destroy(params[:index])
    end
    render :nothing => true
  end

  def attending
    @invitee = Invitee.find_by_uuid(params[:id])
  end

  def not_attending
    @invitee = Invitee.find_by_uuid(params[:id])
  end

  def rsvp_main
    @invitee = Invitee.find_by_uuid(params[:id])
  end

  def rsvp_result
    @invitee = Invitee.find_by_uuid(params[:id])
  end

  def mass_email
    if params[:index] == 'all' 
      @invitees = Invitee.all
    else
      @invitees = Invitee.find(params[:index])
    end
    @invitees.each do |invitee|
      # SendEmailJob.perform_later(@invitee)
      WeddingMailer.invitation_email(invitee).deliver
    end
    respond_to do |format|
      format.js
    end
  end

  def import
    Invitee.import(params[:file])
    render :nothing => true
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invitee
      #@invitee = Invitee.find(params[:id])
      @invitee = Invitee.find_by_uuid(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invitee_params
      params.require(:invitee).permit(:name, :number, :attending, :uuid, :email ,:is_attending_patch, :addressee)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to invitees_path
      # Log the user in and redirect to the user's show page.
    else
      # Create an error message.
      flash.now[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end
  
  def destroy
    log_out if logged_in?
    redirect_to invitees_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invitees_helper.rb
module InviteesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/invitees/_attending.html.erb
<%= form_for(@invitee, :html => { class: 'form-horizontal', role: 'form' }) do |f| %>
  <% if @invitee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invitee.errors.count, "error") %> prohibited this invitee from being saved:</h2>
      <ul>
      <% @invitee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label for="invitee_number" class="col-sm-3 control-label">How many guests will be attending?</label>
    <div class="col-sm-6 col-xs-6 col-md-2">
      <div class="col-sm-10 col-xs-12 col-md-9">
        <%= f.text_field :number, value: (@invitee.number || '1'), class: "form-control rsvp_input" %>
      </div>
    </div>
  </div>
  
  <div class="field">
    <%= f.hidden_field :is_attending_patch, value: true %>
  </div>

  <div class="form-group">
    <div class="col-sm-4">
      <%= f.submit 'Submit', class: 'btn btn-primary'%>
    </div>
  </div>
<% end %>

<script>
  $("#invitee_number").TouchSpin({
    min: 1,
    max: <%= @invitee.max_guests %>,
    verticalupclass: 'glyphicon glyphicon-plus',
    verticaldownclass: 'glyphicon glyphicon-minus'
  });
</script>

app/views/invitees/_form.html.erb
<%= form_for(@invitee) do |f| %>
  <% if @invitee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invitee.errors.count, "error") %> prohibited this invitee from being saved:</h2>

      <ul>
      <% @invitee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :addressee %><br>
    <%= f.text_field :addressee %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :attending %><br>
    <%= f.check_box :attending %>
  </div>
  <div class="field">
    <%= f.hidden_field :uuid, value: @invitee.uuid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invitees/_not_attending.html.erb
<%= form_for(@invitee, :html => { class: 'form-horizontal', role: 'form' }) do |f| %>
  <% if @invitee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invitee.errors.count, "error") %> prohibited this invitee from being saved:</h2>

      <ul>
      <% @invitee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :attending, value: false %>
  </div>

  <div class="field">
    <%= f.hidden_field :is_attending_patch, value: true %>
  </div>

  <div class="form-group">
    <div class="col-sm-4">
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/invitees/edit.html.erb
<h1>Editing invitee</h1>

<%= render 'form' %>

<%= link_to 'Show', @invitee %> |
<%= link_to 'Back', invitees_path %>

app/views/invitees/index.html.erb
<% if logged_in? %>
  <ul class='nav nav-tabs' role='tablist'>
    <li class='active'><%= link_to 'Invitees', invitees_path %></li>
    <li><%= link_to "Log out", logout_path, method: "delete" %></li>
  </ul>


  <h1>Listing Invitees</h1>

  <table id='invitees' data-source="<%= index_datatable_url(format: "json") %>" class="hover stripe">
    <thead>
      <tr>
        <th>Select</th>
        <th>Name</th>
        <th>Addressee</th>
        <th>Email</th>
        <th>Number</th>
        <th>Max Guests</th>
        <th>Attending</th>
        <th>RSVP</th>
        <th>Edit</th>
        <th>Destroy</th>
      </tr>
    </thead>
    <tfoot>
      <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td id='total_number'></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
    </tfoot>
    <tbody>
    </tbody>
  </table>
  
  </br>

  <%= link_to new_invitee_path, class: 'btn btn-primary' do %>
    <i class='glyphicon glyphicon-plus'></i> New Invitee
  <% end %>
  <%= form_tag mass_email_invitees_path, method: :post, data: { confirm: 'Email all selected?' }, id: 'email_selected_form', style: 'display:inline; margin:0px; padding:0px;', remote: true do %>
    <%= button_tag(class: 'btn btn-primary') do %>
      <i class='fa fa-envelope'></i> Email Selected
    <% end %>
  <% end %>
  <%= link_to mass_email_invitees_path, method: :post, data: { confirm: 'Send all invitations?' }, :remote => true, class: 'btn btn-primary', id: 'email_all_invitations' do %>
    <i class='fa fa-envelope'></i> Email All Invitees
  <% end %>
  
  <form class='btn btn-primary dropzone dz-clickable' id='dropzone_div'>
    <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
  </form>

  <div id="email_response"><ul id="email_response_list"></ul></div>
<% else %>
  <ul class='nav nav-tabs' role='tablist'>
    <li class='active'><%= link_to "Log in", login_path, class: 'btn btn-primary' %></li>
  </ul>
<% end %>

app/views/invitees/mass_email.js.erb
$('#email_response_heading').remove();
$('.email_invitee').remove();

<% @invitees.each do |invitee| %>
  $('#email_response_list').append('<li class="email_invitee"> <%= j invitee.name.html_safe %> </li> ')
<% end %>
$('#email_response').prepend('<h3 id="email_response_heading">Email sent to:</h3>');

app/views/invitees/new.html.erb
<h1>New invitee</h1>

<%= render 'form' %>

<%= link_to 'Back', invitees_path %>

app/views/invitees/rsvp_main.html.erb
<%= provide :title, @invitee.addressee %>

<p>
  Welcome <%= @invitee.addressee %>,
</p>
<p>
  Will you be attending Megan and Jonathan's wedding?
</p>

<ul class="nav nav-tabs">
    <li> <a href="#attending" data-target="#attending" data-toggle="tab">Attending</a>
    </li>
    <li><a href="#not_attending" data-target="#not_attending" data-toggle="tab">Not Attending</a>
    </li>
</ul>

<div class="tab-content">
  <div class="tab-pane fade" id="attending"><%= render 'attending' %></div>
  <div class="tab-pane fade" id="not_attending"><%= render 'not_attending' %></div>
</div>

app/views/invitees/rsvp_result.html.erb
<%= provide :title, @invitee.addressee %>

<p>
  <%= @invitee.addressee %>, thank you for your RSVP.
</p>

<% if @invitee.attending %>
  We are so glad that you could join us.
<% else %>
  We are so sorry that you won't be joining us.
<% end %>

app/views/invitees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @invitee.name %>
</p>

<p>
  <strong>Number:</strong>
  <%= @invitee.number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @invitee.email %>
</p>

<p>
  <strong>Attending:</strong>
  <%= @invitee.attending %>
</p>

<p>
  <strong>Uuid:</strong>
  <%= @invitee.uuid %>
</p>

<%= link_to 'Edit', edit_invitee_path(@invitee) %> |
<%= link_to 'Back', invitees_path %>

app/views/layouts/_footer.html.erb
<% if request.original_url =~ /rsvp_main/ %>
  <div class="rsvp-footer">
<% else %>
  <div class='footer-wrapper'>
<% end %>
  <div class="container">
    <!-- Footer -->
    <footer>
      <div class="row">
        <div class="col-lg-12">
          <ul class='inline credits'>
            <li class='footer-title'>Design, Development, & Code By <a href='http://www.bobbidydoo.co.za/' class='footer-link'>Jonathan Frankel</a></li>
          </ul>
        </div>
      </div>
    </footer>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %> | MJF </title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  
</head>
<body>
  <%= render 'shared/navigation' %>

  <div class="container-fluid">
    <div id='main'>
      <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
      <%= yield %>
    </div>
  </div>
  <%= render 'layouts/footer' %>

</body>
</html>

app/views/shared/_navigation.html.erb
<nav class='navbar navbar-default' role='navigation'>
  <div class='navbar-header'>
    <%= link_to invitees_path do %>
      <%= image_tag image_path('mjf.png'), height: '90%', width: '90%', style: 'max-width:100px' %>
    <% end %>
  </div>
</nav>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>